### ISSUE TITLE
Issues on the evaluation side (add_template.py)

### ISSUE THREAD

**Issue by TusharAggarwalMSR** [CodeEditorBench/CodeEditorBench#2]
1. model_name should be replaced by model in line 621
2. code1=inp["code"] should be replaced by code1=inp["code"][0] in line 644 as the code is being saved in a list inside jsonl file

**Comment by mkj3085003** [comment]
I've addressed the small issue in the add_template.py script at line 711 and made the necessary updates. Please feel free to try out the newly updated code. Thank you for bringing this to our attention, and don't hesitate to let us know if you notice any new issues during runtime. Your feedback is greatly appreciated!

**Comment by AggarwalTushar** [comment]
@mkj3085003 I couldn't see the suggested changes in the newly updated code, still facing these issues.

**Comment by mkj3085003** [comment]
Can you please take a screenshot to show your detailed error message?

**Comment by mkj3085003** [comment]
If you've already submitted a solution to the database before, it's likely that the database will hold previous records that will affect the current run, so you can try pulling the image again.

**Comment by mkj3085003** [comment]
I've verified this evaluation process from scratch, and the add_template script is executing correctly, and the results that appear in the image below indicate that it's running correctly. Maybe pull the image and code from scratch and try again? Or give some more detail on the issue and I can help you out.
<img width="856" alt="1" src="https://github.com/CodeEditorBench/CodeEditorBench/assets/93718766/4aff0066-800f-4942-9be4-25ed86e243e5">

**Comment by AggarwalTushar** [comment]
As suggested by you, I am able to run the add_template file when I create the image again. I was trying to run evaluation for code_debug, and followed the steps given in the readme file. But the count of unsolved solutions is not decreasing over time. I have tried waiting for few hrs. I am also attaching a SS for your reference.

![compute_metrics py - tushar  SSH_ 10 219 206 11  - Visual Studio Code 4_17_2024 3_57_05 PM](https://github.com/CodeEditorBench/CodeEditorBench/assets/62869434/c86ddf35-edd7-48fb-a598-2252470f2d6d)

**Comment by mkj3085003** [comment]
I would like to confirm whether your issue has been resolved. We are currently considering optimizing the entire evalution process, and your suggestions would be very helpful to us. Looking forward to hearing from you.

**Comment by AggarwalTushar** [comment]
> I would like to confirm whether your issue has been resolved. We are currently considering optimizing the entire evalution process, and your suggestions would be very helpful to us. Looking forward to hearing from you.

I am facing the same issues as in #6.
